### ISSUE TITLE
CreateInventoryTaskRequest using LMS_ACTIVE_INVENTORY_REPORT empty response

### ISSUE THREAD

**Issue by sunil11475-dev** [zVPS/ebay-sell-inventory-php-client#1]
I have trying to make call for **CreateInventoryTaskRequest** using **LMS_ACTIVE_INVENTORY_REPORT** but getting empty response.

I am using example code from [https://github.com/zVPS/ebay-sell-feed-php-client/blob/main/docs/Api/InventoryTaskApi.md]

When i try in API Explorer it showing empty **Response Body** but can see the file link in **Response Headers**. 

Please find the attached file. 
![Untitled](https://user-images.githubusercontent.com/82319811/184645992-8eee6ba1-88f7-4e17-a7fa-440cf4eac581.png)

if i can't get Response Body than can you please show me how to get Response Headers in - 

```
try {
    $apiInstance->createInventoryTask($body, $x_ebay_c_marketplace_id);
} catch (Exception $e) {
    echo 'Exception when calling InventoryTaskApi->createInventoryTask: ', $e->getMessage(), PHP_EOL;
}
```

**Comment by Caffe1neAdd1ct** [comment]
Have a look at https://github.com/zVPS/ebay-sell-feed-php-client/blob/77ce2f898c5584ebed9125ee8f9e0132439e5767/lib/Api/InventoryTaskApi.php#L143

There are functions which will return the Http info such as headers, which will hopefully do what you're looking for.

**Comment by sunil11475-dev** [comment]
Hi @Caffe1neAdd1ct 
Hope you are well. I have tried already when $response = $this->client->send($request, $options); coming empty then how can i get header?

**Comment by Caffe1neAdd1ct** [comment]
I'm good thanks, busy as always, you?

So when you're doing:

```
$response = $apiInstance->createInventoryTask($body, $x_ebay_c_marketplace_id);
```

can you try:

```
$responseInfo = $apiInstance->createInventoryTaskWithHttpInfo($body, $x_ebay_c_marketplace_id);
```

$responseInfo should be an array with the response headers in key `2`, status in key `1` and body in key `0` which in this case is null.

```
return [null, $statusCode, $response->getHeaders()];
```

**Comment by sunil11475-dev** [comment]
You are rock star. Worked perfectly. 

Thanks again for your help.
